spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb/lanchonete
    username: username
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    database: H2


server:
  servlet:
    context-path: /lanchonete-produto/api/v1
  host: http://localhost
  port: 8080
